services:
  backend:
    build:
      context: ./backend
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    networks:
      - taskmaster_network
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "0.5"

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env.docker
    depends_on:
      - backend
    networks:
      - taskmaster_network
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "0.5"

networks:
  taskmaster_network:
    driver: bridge
